[package]
name = "wasm-bench-benchmarks"
version = "0.1.0"
authors = ["The Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
sha1 = "0.6.0"
